// Code generated by generate_ddr_cli.py. DO NOT EDIT.

package externaldevice_policy

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/ddr/ddr-cli-generated/products/ddr/client"
	"github.com/spf13/cobra"
)

type CreateCmdParams struct {
	Name             string                 `json:"name"`               // 策略名
	Description      string                 `json:"description"`        // 策略描述
	PeriodCategory   string                 `json:"period_category"`    // 生效周期
	Scope            string                 `json:"scope"`              // 下发范围 全局：global 部分：common
	Access           map[string]interface{} `json:"access"`             // 实际管控外设
	Action           string                 `json:"action"`             // 处置动作
	ActionTemplate   map[string]interface{} `json:"action_template"`    // 详细处置动作
	BindingConfig    map[string]interface{} `json:"binding_config"`     // 绑定配置
	ActionTemplateId string                 `json:"action_template_id"` // 处置模板ID
}

var create_params CreateCmdParams
var CreateAccessJSON string
var CreateActionTemplateJSON string
var CreateBindingConfigJSON string

var CreateCmd = &cobra.Command{
	Use:   "create",
	Short: "创建外设管控策略",
	Long:  `创建外设管控策略`,
	RunE: func(cmd *cobra.Command, args []string) error {
		if CreateAccessJSON != "" {
			if err := json.Unmarshal([]byte(CreateAccessJSON), &create_params.Access); err != nil {
				return fmt.Errorf("parse access: %w", err)
			}
		}
		if CreateActionTemplateJSON != "" {
			if err := json.Unmarshal([]byte(CreateActionTemplateJSON), &create_params.ActionTemplate); err != nil {
				return fmt.Errorf("parse action-template: %w", err)
			}
		}
		if CreateBindingConfigJSON != "" {
			if err := json.Unmarshal([]byte(CreateBindingConfigJSON), &create_params.BindingConfig); err != nil {
				return fmt.Errorf("parse binding-config: %w", err)
			}
		}
		pathParams := map[string]interface{}{}

		queryParams := map[string]interface{}{}

		body := map[string]interface{}{}
		if cmd.Flags().Changed("name") {
			body["name"] = create_params.Name
		}
		if cmd.Flags().Changed("description") {
			body["description"] = create_params.Description
		}
		if cmd.Flags().Changed("period-category") {
			body["period_category"] = create_params.PeriodCategory
		}
		if cmd.Flags().Changed("scope") {
			body["scope"] = create_params.Scope
		}
		if cmd.Flags().Changed("access") {
			body["access"] = create_params.Access
		}
		if cmd.Flags().Changed("action") {
			body["action"] = create_params.Action
		}
		if cmd.Flags().Changed("action-template") {
			body["action_template"] = create_params.ActionTemplate
		}
		if cmd.Flags().Changed("binding-config") {
			body["binding_config"] = create_params.BindingConfig
		}
		if cmd.Flags().Changed("action-template-id") {
			body["action_template_id"] = create_params.ActionTemplateId
		}
		return client.GetClient().Do(cmd, context.Background(), "POST", "/v1/policy/externaldevice/create", pathParams, queryParams, body)
	},
}

func init() {
	CreateCmd.Flags().StringVar(&create_params.Name, "name", "", "策略名")
	CreateCmd.Flags().StringVar(&create_params.Description, "description", "", "策略描述")
	CreateCmd.Flags().StringVar(&create_params.PeriodCategory, "period-category", "", "生效周期")
	CreateCmd.Flags().StringVar(&create_params.Scope, "scope", "", "下发范围 全局：global 部分：common")
	CreateCmd.Flags().StringVar(&CreateAccessJSON, "access", "", "实际管控外设 (JSON, e.g. {\"external_disk\": \"\"})")
	CreateCmd.Flags().StringVar(&create_params.Action, "action", "", "处置动作")
	CreateCmd.Flags().StringVar(&CreateActionTemplateJSON, "action-template", "", "详细处置动作 (JSON, e.g. {\"label\": \"\", \"value\": \"\", \"key\": \"\"})")
	CreateCmd.Flags().StringVar(&CreateBindingConfigJSON, "binding-config", "", "绑定配置 (JSON, e.g. {\"source\": \"\", \"include\": {\"dept_ids\": [\"\"], \"staff_ids\": [\"\"], \"staff_tag_ids\": [\"\"], \"device_ids\": [\"\"], \"device_tag_ids\": [\"\"]}, \"exclude\": {}})")
	CreateCmd.Flags().StringVar(&create_params.ActionTemplateId, "action-template-id", "", "处置模板ID")
	_ = CreateCmd.MarkFlagRequired("name")
	_ = CreateCmd.MarkFlagRequired("period-category")
	_ = CreateCmd.MarkFlagRequired("scope")
	_ = CreateCmd.MarkFlagRequired("access")
	_ = CreateCmd.MarkFlagRequired("action")
	_ = CreateCmd.MarkFlagRequired("action-template")
	_ = CreateCmd.MarkFlagRequired("binding-config")
	_ = CreateCmd.MarkFlagRequired("action-template-id")
}
