// Code generated by generate_ddr_cli.py. DO NOT EDIT.

package externaldevice_policy

import "github.com/spf13/cobra"

var ExternaldevicePolicyCmd = &cobra.Command{
	Use:   "externaldevice_policy",
	Short: "外设管控策略",
	Long:  `外设管控策略相关命令。`,
}

func init() {
	ExternaldevicePolicyCmd.AddCommand(CreateCmd)
	ExternaldevicePolicyCmd.AddCommand(DeleteCmd)
	ExternaldevicePolicyCmd.AddCommand(StatusUpdateCmd)
}
