// Code generated by generate_ddr_cli.py. DO NOT EDIT.

package approval

import "github.com/spf13/cobra"

var ApprovalCmd = &cobra.Command{
	Use:   "approval",
	Short: "文件外发审批",
	Long:  `文件外发审批相关命令。`,
}

func init() {
	ApprovalCmd.AddCommand(InstanceCreateCmd)
	ApprovalCmd.AddCommand(InstanceActionCmd)
}
