// Code generated by generate_ddr_cli.py. DO NOT EDIT.

package approval

import (
	"context"

	"github.com/ddr/ddr-cli-generated/products/ddr/client"
	"github.com/spf13/cobra"
)

type InstanceActionCmdParams struct {
	InstanceId     string `json:"instance_id"`     // 审批实例ID
	ApprovalStatus string `json:"approval_status"` // 审批状态，可选值为approved（通过）或rejected（拒绝）
	Opinions       string `json:"opinions"`        // 审批意见
}

var instance_action_params InstanceActionCmdParams

var InstanceActionCmd = &cobra.Command{
	Use:   "instance_action",
	Short: "审批通过/拒绝",
	Long:  `审批通过/拒绝`,
	RunE: func(cmd *cobra.Command, args []string) error {

		pathParams := map[string]interface{}{}
		pathParams["instance_id"] = instance_action_params.InstanceId
		queryParams := map[string]interface{}{}

		body := map[string]interface{}{}
		if cmd.Flags().Changed("approval-status") {
			body["approval_status"] = instance_action_params.ApprovalStatus
		}
		if cmd.Flags().Changed("opinions") {
			body["opinions"] = instance_action_params.Opinions
		}
		return client.GetClient().Do(cmd, context.Background(), "POST", "/v1/approval/instance/{instance_id}/action", pathParams, queryParams, body)
	},
}

func init() {
	InstanceActionCmd.Flags().StringVar(&instance_action_params.InstanceId, "instance-id", "", "审批实例ID")
	InstanceActionCmd.Flags().StringVar(&instance_action_params.ApprovalStatus, "approval-status", "", "审批状态，可选值为approved（通过）或rejected（拒绝）")
	InstanceActionCmd.Flags().StringVar(&instance_action_params.Opinions, "opinions", "", "审批意见")
	_ = InstanceActionCmd.MarkFlagRequired("instance-id")
	_ = InstanceActionCmd.MarkFlagRequired("approval-status")
	_ = InstanceActionCmd.MarkFlagRequired("opinions")
}
