// Code generated by generate_ddr_cli.py. DO NOT EDIT.

package approval

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/ddr/ddr-cli-generated/products/ddr/client"
	"github.com/spf13/cobra"
)

type InstanceCreateCmdParams struct {
	ApprovalOptions map[string]interface{} `json:"approval_options"` // 审批选项配置
	Reason          string                 `json:"reason"`           // 申请理由
	DeviceId        string                 `json:"device_id"`        // 设备UUID
}

var instance_create_params InstanceCreateCmdParams
var InstanceCreateApprovalOptionsJSON string

var InstanceCreateCmd = &cobra.Command{
	Use:   "instance_create",
	Short: "创建审批",
	Long:  `创建审批`,
	RunE: func(cmd *cobra.Command, args []string) error {
		if InstanceCreateApprovalOptionsJSON != "" {
			if err := json.Unmarshal([]byte(InstanceCreateApprovalOptionsJSON), &instance_create_params.ApprovalOptions); err != nil {
				return fmt.Errorf("parse approval-options: %w", err)
			}
		}
		pathParams := map[string]interface{}{}

		queryParams := map[string]interface{}{}

		body := map[string]interface{}{}
		if cmd.Flags().Changed("approval-options") {
			body["approval_options"] = instance_create_params.ApprovalOptions
		}
		if cmd.Flags().Changed("reason") {
			body["reason"] = instance_create_params.Reason
		}
		if cmd.Flags().Changed("device-id") {
			body["device_id"] = instance_create_params.DeviceId
		}
		return client.GetClient().Do(cmd, context.Background(), "POST", "/v1/approval/instance/create", pathParams, queryParams, body)
	},
}

func init() {
	InstanceCreateCmd.Flags().StringVar(&InstanceCreateApprovalOptionsJSON, "approval-options", "", "审批选项配置 (JSON, e.g. {\"channels\": [{\"uid\": \"\", \"name\": \"\"}], \"valid_duration\": {\"value\": 0, \"unit\": \"\"}, \"times\": 0, \"files\": [{\"filename\": \"\", \"filesize\": 0, \"filepath\": \"\", \"file_suffix\": \"\", \"md5_hash\": \"\"}]})")
	InstanceCreateCmd.Flags().StringVar(&instance_create_params.Reason, "reason", "", "申请理由")
	InstanceCreateCmd.Flags().StringVar(&instance_create_params.DeviceId, "device-id", "", "设备UUID")
	_ = InstanceCreateCmd.MarkFlagRequired("approval-options")
	_ = InstanceCreateCmd.MarkFlagRequired("reason")
	_ = InstanceCreateCmd.MarkFlagRequired("device-id")
}
