// Code generated by generate_ddr_cli.py. DO NOT EDIT.

package channel

import "github.com/spf13/cobra"

var ChannelCmd = &cobra.Command{
	Use:   "channel",
	Short: "渠道源管理",
	Long:  `渠道源管理相关命令。`,
}

func init() {
	ChannelCmd.AddCommand(ListCmd)
}
