// Code generated by generate_ddr_cli.py. DO NOT EDIT.

package channel

import (
	"context"

	"github.com/ddr/ddr-cli-generated/products/ddr/client"
	"github.com/spf13/cobra"
)

type ListCmdParams struct {
}

var list_params ListCmdParams

var ListCmd = &cobra.Command{
	Use:   "list",
	Short: "查询渠道源列表",
	Long:  `查询渠道源列表`,
	RunE: func(cmd *cobra.Command, args []string) error {

		pathParams := map[string]interface{}{}

		queryParams := map[string]interface{}{}

		return client.GetClient().Do(cmd, context.Background(), "POST", "/v1/channel/list", pathParams, queryParams, nil)
	},
}

func init() {

}
