// Code generated by generate_ddr_cli.py. DO NOT EDIT.

package token

import (
	"context"

	"github.com/ddr/ddr-cli-generated/products/ddr/client"
	"github.com/spf13/cobra"
)

type CreateCmdParams struct {
	ClientId     string `json:"client_id"`     // AccessKey ID
	ClientSecret string `json:"client_secret"` // AccessKey Secret
	ExpiresIn    int    `json:"expires_in"`    // 自定义 access_token时长，单位为秒，最小值为 7200（2 小时），最大值为 315360000（10 年）。默认是 7200。
}

var create_params CreateCmdParams

var CreateCmd = &cobra.Command{
	Use:   "create",
	Short: "获取访问凭证",
	Long:  `获取访问凭证`,
	RunE: func(cmd *cobra.Command, args []string) error {

		pathParams := map[string]interface{}{}

		queryParams := map[string]interface{}{}

		body := map[string]interface{}{}
		if cmd.Flags().Changed("client-id") {
			body["client_id"] = create_params.ClientId
		}
		if cmd.Flags().Changed("client-secret") {
			body["client_secret"] = create_params.ClientSecret
		}
		if cmd.Flags().Changed("expires-in") {
			body["expires_in"] = create_params.ExpiresIn
		}
		return client.GetClient().Do(cmd, context.Background(), "POST", "/v1/token", pathParams, queryParams, body)
	},
}

func init() {
	CreateCmd.Flags().StringVar(&create_params.ClientId, "client-id", "", "AccessKey ID")
	CreateCmd.Flags().StringVar(&create_params.ClientSecret, "client-secret", "", "AccessKey Secret")
	CreateCmd.Flags().IntVar(&create_params.ExpiresIn, "expires-in", 0, "自定义 access_token时长，单位为秒，最小值为 7200（2 小时），最大值为 315360000（10 年）。默认是 7200。")
	_ = CreateCmd.MarkFlagRequired("client-id")
	_ = CreateCmd.MarkFlagRequired("client-secret")
}
