// Code generated by generate_ddr_cli.py. DO NOT EDIT.

package token

import "github.com/spf13/cobra"

var TokenCmd = &cobra.Command{
	Use:   "token",
	Short: "访问凭证",
	Long:  `访问凭证相关命令。`,
}

func init() {
	TokenCmd.AddCommand(CreateCmd)
}
