// Code generated by generate_ddr_cli.py. DO NOT EDIT.

package stafftag

import (
	"context"

	"github.com/ddr/ddr-cli-generated/products/ddr/client"
	"github.com/spf13/cobra"
)

type CreateCmdParams struct {
	Name string `json:"name"` // 标签名
}

var create_params CreateCmdParams

var CreateCmd = &cobra.Command{
	Use:   "create",
	Short: "创建员工标签",
	Long:  `创建员工标签`,
	RunE: func(cmd *cobra.Command, args []string) error {

		pathParams := map[string]interface{}{}

		queryParams := map[string]interface{}{}

		body := map[string]interface{}{}
		if cmd.Flags().Changed("name") {
			body["name"] = create_params.Name
		}
		return client.GetClient().Do(cmd, context.Background(), "POST", "/v1/stafftag/create", pathParams, queryParams, body)
	},
}

func init() {
	CreateCmd.Flags().StringVar(&create_params.Name, "name", "", "标签名")
	_ = CreateCmd.MarkFlagRequired("name")
}
