// Code generated by generate_ddr_cli.py. DO NOT EDIT.

package stafftag

import (
	"context"

	"github.com/ddr/ddr-cli-generated/products/ddr/client"
	"github.com/spf13/cobra"
)

type DeleteCmdParams struct {
	TagId string `json:"tag_id"` // 标签唯一ID
}

var delete_params DeleteCmdParams

var DeleteCmd = &cobra.Command{
	Use:   "delete",
	Short: "删除员工标签",
	Long:  `删除员工标签`,
	RunE: func(cmd *cobra.Command, args []string) error {

		pathParams := map[string]interface{}{}

		queryParams := map[string]interface{}{}

		body := map[string]interface{}{}
		if cmd.Flags().Changed("tag-id") {
			body["tag_id"] = delete_params.TagId
		}
		return client.GetClient().Do(cmd, context.Background(), "POST", "/v1/stafftag/delete", pathParams, queryParams, body)
	},
}

func init() {
	DeleteCmd.Flags().StringVar(&delete_params.TagId, "tag-id", "", "标签唯一ID")
	_ = DeleteCmd.MarkFlagRequired("tag-id")
}
