// Code generated by generate_ddr_cli.py. DO NOT EDIT.

package stafftag

import (
	"context"

	"github.com/ddr/ddr-cli-generated/products/ddr/client"
	"github.com/spf13/cobra"
)

type MemberBatchRemoveCmdParams struct {
	TagId    string   `json:"tag_id"`    // 标签ID
	StaffIds []string `json:"staff_ids"` // 员工ID列表
}

var member_batch_remove_params MemberBatchRemoveCmdParams

var MemberBatchRemoveCmd = &cobra.Command{
	Use:   "member_batch_remove",
	Short: "员工标签批量移除员工",
	Long:  `员工标签批量移除员工`,
	RunE: func(cmd *cobra.Command, args []string) error {

		pathParams := map[string]interface{}{}

		queryParams := map[string]interface{}{}

		body := map[string]interface{}{}
		if cmd.Flags().Changed("tag-id") {
			body["tag_id"] = member_batch_remove_params.TagId
		}
		if cmd.Flags().Changed("staff-ids") {
			body["staff_ids"] = member_batch_remove_params.StaffIds
		}
		return client.GetClient().Do(cmd, context.Background(), "POST", "/v1/stafftag/member/batch_remove", pathParams, queryParams, body)
	},
}

func init() {
	MemberBatchRemoveCmd.Flags().StringVar(&member_batch_remove_params.TagId, "tag-id", "", "标签ID")
	MemberBatchRemoveCmd.Flags().StringSliceVar(&member_batch_remove_params.StaffIds, "staff-ids", nil, "员工ID列表")
	_ = MemberBatchRemoveCmd.MarkFlagRequired("tag-id")
	_ = MemberBatchRemoveCmd.MarkFlagRequired("staff-ids")
}
