// Code generated by generate_ddr_cli.py. DO NOT EDIT.

package stafftag

import (
	"context"

	"github.com/ddr/ddr-cli-generated/products/ddr/client"
	"github.com/spf13/cobra"
)

type MemberBatchAddCmdParams struct {
	TagId    string   `json:"tag_id"`    // 标签ID
	StaffIds []string `json:"staff_ids"` // 被绑定的员工的uid 列表
}

var member_batch_add_params MemberBatchAddCmdParams

var MemberBatchAddCmd = &cobra.Command{
	Use:   "member_batch_add",
	Short: "员工标签批量添加员工",
	Long:  `员工标签批量添加员工`,
	RunE: func(cmd *cobra.Command, args []string) error {

		pathParams := map[string]interface{}{}

		queryParams := map[string]interface{}{}

		body := map[string]interface{}{}
		if cmd.Flags().Changed("tag-id") {
			body["tag_id"] = member_batch_add_params.TagId
		}
		if cmd.Flags().Changed("staff-ids") {
			body["staff_ids"] = member_batch_add_params.StaffIds
		}
		return client.GetClient().Do(cmd, context.Background(), "POST", "/v1/stafftag/member/batch_add", pathParams, queryParams, body)
	},
}

func init() {
	MemberBatchAddCmd.Flags().StringVar(&member_batch_add_params.TagId, "tag-id", "", "标签ID")
	MemberBatchAddCmd.Flags().StringSliceVar(&member_batch_add_params.StaffIds, "staff-ids", nil, "被绑定的员工的uid 列表")
	_ = MemberBatchAddCmd.MarkFlagRequired("tag-id")
	_ = MemberBatchAddCmd.MarkFlagRequired("staff-ids")
}
