// Code generated by generate_ddr_cli.py. DO NOT EDIT.

package stafftag

import "github.com/spf13/cobra"

var StafftagCmd = &cobra.Command{
	Use:   "stafftag",
	Short: "员工标签管理",
	Long:  `员工标签管理相关命令。`,
}

func init() {
	StafftagCmd.AddCommand(ListCmd)
	StafftagCmd.AddCommand(MemberBatchAddCmd)
	StafftagCmd.AddCommand(MemberBatchRemoveCmd)
	StafftagCmd.AddCommand(CreateCmd)
	StafftagCmd.AddCommand(UpdateCmd)
	StafftagCmd.AddCommand(DeleteCmd)
}
