// Code generated by generate_ddr_cli.py. DO NOT EDIT.

package stafftag

import (
	"context"

	"github.com/ddr/ddr-cli-generated/products/ddr/client"
	"github.com/spf13/cobra"
)

type UpdateCmdParams struct {
	TagId string `json:"tag_id"` // 标签ID
	Name  string `json:"name"`   // 标签名
}

var update_params UpdateCmdParams

var UpdateCmd = &cobra.Command{
	Use:   "update",
	Short: "修改员工标签",
	Long:  `修改员工标签`,
	RunE: func(cmd *cobra.Command, args []string) error {

		pathParams := map[string]interface{}{}

		queryParams := map[string]interface{}{}

		body := map[string]interface{}{}
		if cmd.Flags().Changed("tag-id") {
			body["tag_id"] = update_params.TagId
		}
		if cmd.Flags().Changed("name") {
			body["name"] = update_params.Name
		}
		return client.GetClient().Do(cmd, context.Background(), "POST", "/v1/stafftag/update", pathParams, queryParams, body)
	},
}

func init() {
	UpdateCmd.Flags().StringVar(&update_params.TagId, "tag-id", "", "标签ID")
	UpdateCmd.Flags().StringVar(&update_params.Name, "name", "", "标签名")
	_ = UpdateCmd.MarkFlagRequired("tag-id")
	_ = UpdateCmd.MarkFlagRequired("name")
}
