// Code generated by generate_ddr_cli.py. DO NOT EDIT.

package client

import (
	"bytes"
	"context"
	"crypto/tls"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"sort"
	"strings"

	"github.com/spf13/cobra"
)

type Client struct {
	baseURL     string
	companyID   string
	token       string
	language    string
	debug       bool
	insecureTLS bool
	httpClient  *http.Client
}

func NewClient() *Client {
	return &Client{
		httpClient: &http.Client{
			Transport: &http.Transport{
				TLSClientConfig: &tls.Config{},
			},
		},
	}
}

var defaultClient = NewClient()

func GetClient() *Client {
	return defaultClient
}

func SetBaseURL(value string) {
	defaultClient.baseURL = strings.TrimRight(value, "/")
}

func SetCompanyID(value string) {
	defaultClient.companyID = value
}

func SetToken(value string) {
	defaultClient.token = value
}

func SetLanguage(value string) {
	defaultClient.language = value
}

func SetDebug(value bool) {
	defaultClient.debug = value
}

func SetInsecureTLS(value bool) {
	defaultClient.insecureTLS = value
	if transport, ok := defaultClient.httpClient.Transport.(*http.Transport); ok {
		if transport.TLSClientConfig == nil {
			transport.TLSClientConfig = &tls.Config{}
		}
		transport.TLSClientConfig.InsecureSkipVerify = value
	}
}

var dryRun bool

func SetDryRun(value bool) {
	dryRun = value
}

var outputFormat = "json"

func SetFormat(value string) {
	outputFormat = value
}

var noTrunc bool

func SetNoTrunc(value bool) {
	noTrunc = value
}

func (c *Client) Do(cmd *cobra.Command, ctx context.Context, method string, route string, pathParams map[string]interface{}, queryParams map[string]interface{}, body interface{}) error {
	if c.baseURL == "" {
		return fmt.Errorf("base URL is required")
	}

	resolvedPath, err := applyPathParams(route, pathParams)
	if err != nil {
		return err
	}

	requestURL, err := url.Parse(c.baseURL + resolvedPath)
	if err != nil {
		return fmt.Errorf("parse request URL: %w", err)
	}

	values := requestURL.Query()
	for key, value := range queryParams {
		appendQueryValues(values, key, value)
	}
	requestURL.RawQuery = values.Encode()

	var requestBody []byte
	if body != nil {
		requestBody, err = json.Marshal(body)
		if err != nil {
			return fmt.Errorf("marshal request body: %w", err)
		}
	}

	if dryRun {
		return printDryRun(cmd, method, requestURL.String(), c.headersFor(resolvedPath), requestBody)
	}

	req, err := http.NewRequestWithContext(ctx, method, requestURL.String(), bytes.NewReader(requestBody))
	if err != nil {
		return fmt.Errorf("create request: %w", err)
	}
	for key, value := range c.headersFor(resolvedPath) {
		req.Header.Set(key, value)
	}

	resp, err := c.httpClient.Do(req)
	if err != nil {
		return fmt.Errorf("send request: %w", err)
	}
	defer resp.Body.Close()

	responseBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return fmt.Errorf("read response: %w", err)
	}
	if resp.StatusCode >= 400 {
		return fmt.Errorf("HTTP %d: %s", resp.StatusCode, strings.TrimSpace(string(responseBody)))
	}

	var payload map[string]interface{}
	if len(responseBody) == 0 {
		payload = map[string]interface{}{"status": resp.StatusCode}
	} else if err := json.Unmarshal(responseBody, &payload); err != nil {
		payload = map[string]interface{}{"raw": string(responseBody)}
	}

	_, _ = fmt.Fprintln(cmd.OutOrStdout(), PrintResult(payload))
	return nil
}

func (c *Client) headersFor(route string) map[string]string {
	headers := map[string]string{
		"Content-Type": "application/json;charset=utf-8",
	}
	if c.companyID != "" {
		headers["X-CS-Header-Company"] = c.companyID
	}
	if c.language != "" {
		headers["Accept-Language"] = c.language
	}
	if c.debug {
		headers["X-CS-Header-Debug"] = "true"
	}
	if route != "/v1/token" && c.token != "" {
		headers["Authorization"] = "Token " + c.token
	}
	return headers
}

func applyPathParams(route string, pathParams map[string]interface{}) (string, error) {
	resolved := route
	for key, value := range pathParams {
		needle := "{" + key + "}"
		resolved = strings.ReplaceAll(resolved, needle, fmt.Sprint(value))
	}
	if strings.Contains(resolved, "{") || strings.Contains(resolved, "}") {
		return "", fmt.Errorf("unresolved path parameters in %s", route)
	}
	return resolved, nil
}

func appendQueryValues(values url.Values, key string, value interface{}) {
	switch typed := value.(type) {
	case nil:
		return
	case []string:
		for _, item := range typed {
			values.Add(key, item)
		}
	case []int:
		for _, item := range typed {
			values.Add(key, fmt.Sprintf("%d", item))
		}
	case []float64:
		for _, item := range typed {
			values.Add(key, fmt.Sprintf("%v", item))
		}
	case []bool:
		for _, item := range typed {
			values.Add(key, fmt.Sprintf("%t", item))
		}
	default:
		values.Set(key, fmt.Sprint(value))
	}
}

func printDryRun(cmd *cobra.Command, method string, requestURL string, headers map[string]string, requestBody []byte) error {
	headerKeys := make([]string, 0, len(headers))
	for key := range headers {
		headerKeys = append(headerKeys, key)
	}
	sort.Strings(headerKeys)

	_, _ = fmt.Fprintf(cmd.OutOrStdout(), "[DRY-RUN] %s %s\n", method, requestURL)
	_, _ = fmt.Fprintln(cmd.OutOrStdout(), "[DRY-RUN] Headers:")
	for _, key := range headerKeys {
		_, _ = fmt.Fprintf(cmd.OutOrStdout(), "%s: %s\n", key, headers[key])
	}
	if len(requestBody) == 0 {
		_, _ = fmt.Fprintln(cmd.OutOrStdout(), "[DRY-RUN] Body: <empty>")
		return nil
	}

	var pretty bytes.Buffer
	if err := json.Indent(&pretty, requestBody, "", "  "); err == nil {
		_, _ = fmt.Fprintf(cmd.OutOrStdout(), "[DRY-RUN] Body:\n%s\n", pretty.String())
		return nil
	}
	_, _ = fmt.Fprintf(cmd.OutOrStdout(), "[DRY-RUN] Body:\n%s\n", string(requestBody))
	return nil
}

func PrintResult(payload map[string]interface{}) string {
	pretty, err := json.MarshalIndent(payload, "", "  ")
	if err != nil {
		return fmt.Sprintf("%v", payload)
	}
	if outputFormat == "json" || noTrunc {
		return string(pretty)
	}
	return string(pretty)
}

func init() {
	defaultClient = NewClient()
	if outputFormat == "" {
		outputFormat = "json"
	}
	if _, present := os.LookupEnv("DDR_CLI_DRY_RUN"); present {
		dryRun = true
	}
}
