// Code generated by generate_ddr_cli.py. DO NOT EDIT.

package staff

import (
	"context"

	"github.com/ddr/ddr-cli-generated/products/ddr/client"
	"github.com/spf13/cobra"
)

type DeviceMembersCmdParams struct {
	Uid string `json:"uid"` // 员工
}

var device_members_params DeviceMembersCmdParams

var DeviceMembersCmd = &cobra.Command{
	Use:   "device_members",
	Short: "查询员工绑定设备",
	Long:  `查询员工绑定设备`,
	RunE: func(cmd *cobra.Command, args []string) error {

		pathParams := map[string]interface{}{}

		queryParams := map[string]interface{}{}

		body := map[string]interface{}{}
		if cmd.Flags().Changed("uid") {
			body["uid"] = device_members_params.Uid
		}
		return client.GetClient().Do(cmd, context.Background(), "POST", "/v1/staff/device/members", pathParams, queryParams, body)
	},
}

func init() {
	DeviceMembersCmd.Flags().StringVar(&device_members_params.Uid, "uid", "", "员工")
	_ = DeviceMembersCmd.MarkFlagRequired("uid")
}
