// Code generated by generate_ddr_cli.py. DO NOT EDIT.

package staff

import (
	"context"

	"github.com/ddr/ddr-cli-generated/products/ddr/client"
	"github.com/spf13/cobra"
)

type ListCmdParams struct {
	Page   int    `json:"page"`   // 第几页
	Limit  int    `json:"limit"`  // 每页条数，默认100
	Search string `json:"search"` // 模糊检索名称
	Number string `json:"number"` // 工号
	Email  string `json:"email"`  // 邮箱
	Mobile string `json:"mobile"` // 手机号
	Code   string `json:"code"`   // 编码
}

var list_params ListCmdParams

var ListCmd = &cobra.Command{
	Use:   "list",
	Short: "查询员工列表",
	Long: `查询员工列表

说明：工号、邮箱、手机号、code不能同时为空`,
	RunE: func(cmd *cobra.Command, args []string) error {

		pathParams := map[string]interface{}{}

		queryParams := map[string]interface{}{}
		if cmd.Flags().Changed("page") {
			queryParams["page"] = list_params.Page
		}
		if cmd.Flags().Changed("limit") {
			queryParams["limit"] = list_params.Limit
		}
		if cmd.Flags().Changed("search") {
			queryParams["search"] = list_params.Search
		}
		body := map[string]interface{}{}
		if cmd.Flags().Changed("number") {
			body["number"] = list_params.Number
		}
		if cmd.Flags().Changed("email") {
			body["email"] = list_params.Email
		}
		if cmd.Flags().Changed("mobile") {
			body["mobile"] = list_params.Mobile
		}
		if cmd.Flags().Changed("code") {
			body["code"] = list_params.Code
		}
		return client.GetClient().Do(cmd, context.Background(), "POST", "/v1/staff/list", pathParams, queryParams, body)
	},
}

func init() {
	ListCmd.Flags().IntVar(&list_params.Page, "page", 0, "第几页")
	ListCmd.Flags().IntVar(&list_params.Limit, "limit", 0, "每页条数，默认100")
	ListCmd.Flags().StringVar(&list_params.Search, "search", "", "模糊检索名称")
	ListCmd.Flags().StringVar(&list_params.Number, "number", "", "工号")
	ListCmd.Flags().StringVar(&list_params.Email, "email", "", "邮箱")
	ListCmd.Flags().StringVar(&list_params.Mobile, "mobile", "", "手机号")
	ListCmd.Flags().StringVar(&list_params.Code, "code", "", "编码")
}
