// Code generated by generate_ddr_cli.py. DO NOT EDIT.

package staff

import "github.com/spf13/cobra"

var StaffCmd = &cobra.Command{
	Use:   "staff",
	Short: "员工管理",
	Long:  `员工管理相关命令。`,
}

func init() {
	StaffCmd.AddCommand(ListCmd)
	StaffCmd.AddCommand(DeviceMembersCmd)
}
