// Code generated by generate_ddr_cli.py. DO NOT EDIT.

package device

import (
	"context"

	"github.com/ddr/ddr-cli-generated/products/ddr/client"
	"github.com/spf13/cobra"
)

type BindingDeleteCmdParams struct {
	DeviceId string `json:"device_id"` // 设备唯一 ID
	StaffId  string `json:"staff_id"`  // 解除绑定的用户的 ID
}

var binding_delete_params BindingDeleteCmdParams

var BindingDeleteCmd = &cobra.Command{
	Use:   "binding_delete",
	Short: "解除设备用户绑定",
	Long:  `解除设备用户绑定`,
	RunE: func(cmd *cobra.Command, args []string) error {

		pathParams := map[string]interface{}{}

		queryParams := map[string]interface{}{}

		body := map[string]interface{}{}
		if cmd.Flags().Changed("device-id") {
			body["device_id"] = binding_delete_params.DeviceId
		}
		if cmd.Flags().Changed("staff-id") {
			body["staff_id"] = binding_delete_params.StaffId
		}
		return client.GetClient().Do(cmd, context.Background(), "POST", "/v1/device/binding/delete", pathParams, queryParams, body)
	},
}

func init() {
	BindingDeleteCmd.Flags().StringVar(&binding_delete_params.DeviceId, "device-id", "", "设备唯一 ID")
	BindingDeleteCmd.Flags().StringVar(&binding_delete_params.StaffId, "staff-id", "", "解除绑定的用户的 ID")
	_ = BindingDeleteCmd.MarkFlagRequired("device-id")
	_ = BindingDeleteCmd.MarkFlagRequired("staff-id")
}
