// Code generated by generate_ddr_cli.py. DO NOT EDIT.

package device

import (
	"context"

	"github.com/ddr/ddr-cli-generated/products/ddr/client"
	"github.com/spf13/cobra"
)

type BindingDetailCmdParams struct {
	DeviceId string `json:"device_id"` // 设备唯一 ID
}

var binding_detail_params BindingDetailCmdParams

var BindingDetailCmd = &cobra.Command{
	Use:   "binding_detail",
	Short: "查询设备当前绑定用户",
	Long:  `查询设备当前绑定用户`,
	RunE: func(cmd *cobra.Command, args []string) error {

		pathParams := map[string]interface{}{}

		queryParams := map[string]interface{}{}

		body := map[string]interface{}{}
		if cmd.Flags().Changed("device-id") {
			body["device_id"] = binding_detail_params.DeviceId
		}
		return client.GetClient().Do(cmd, context.Background(), "POST", "/v1/device/binding/detail", pathParams, queryParams, body)
	},
}

func init() {
	BindingDetailCmd.Flags().StringVar(&binding_detail_params.DeviceId, "device-id", "", "设备唯一 ID")
	_ = BindingDetailCmd.MarkFlagRequired("device-id")
}
