// Code generated by generate_ddr_cli.py. DO NOT EDIT.

package device

import (
	"context"

	"github.com/ddr/ddr-cli-generated/products/ddr/client"
	"github.com/spf13/cobra"
)

type BindingUpdateCmdParams struct {
	DeviceId string `json:"device_id"` // 设备唯一 ID
	StaffId  string `json:"staff_id"`  // 绑定用户的 ID
}

var binding_update_params BindingUpdateCmdParams

var BindingUpdateCmd = &cobra.Command{
	Use:   "binding_update",
	Short: "更新设备当前绑定用户",
	Long:  `更新设备当前绑定用户`,
	RunE: func(cmd *cobra.Command, args []string) error {

		pathParams := map[string]interface{}{}

		queryParams := map[string]interface{}{}

		body := map[string]interface{}{}
		if cmd.Flags().Changed("device-id") {
			body["device_id"] = binding_update_params.DeviceId
		}
		if cmd.Flags().Changed("staff-id") {
			body["staff_id"] = binding_update_params.StaffId
		}
		return client.GetClient().Do(cmd, context.Background(), "POST", "/v1/device/binding/update", pathParams, queryParams, body)
	},
}

func init() {
	BindingUpdateCmd.Flags().StringVar(&binding_update_params.DeviceId, "device-id", "", "设备唯一 ID")
	BindingUpdateCmd.Flags().StringVar(&binding_update_params.StaffId, "staff-id", "", "绑定用户的 ID")
	_ = BindingUpdateCmd.MarkFlagRequired("device-id")
	_ = BindingUpdateCmd.MarkFlagRequired("staff-id")
}
