// Code generated by generate_ddr_cli.py. DO NOT EDIT.

package device

import (
	"context"

	"github.com/ddr/ddr-cli-generated/products/ddr/client"
	"github.com/spf13/cobra"
)

type DetailCmdParams struct {
	DeviceId string `json:"device_id"` // 设备ID
}

var detail_params DetailCmdParams

var DetailCmd = &cobra.Command{
	Use:   "detail",
	Short: "查询设备详情",
	Long:  `查询设备详情`,
	RunE: func(cmd *cobra.Command, args []string) error {

		pathParams := map[string]interface{}{}

		queryParams := map[string]interface{}{}

		body := map[string]interface{}{}
		if cmd.Flags().Changed("device-id") {
			body["device_id"] = detail_params.DeviceId
		}
		return client.GetClient().Do(cmd, context.Background(), "POST", "/v1/device/detail", pathParams, queryParams, body)
	},
}

func init() {
	DetailCmd.Flags().StringVar(&detail_params.DeviceId, "device-id", "", "设备ID")
	_ = DetailCmd.MarkFlagRequired("device-id")
}
