// Code generated by generate_ddr_cli.py. DO NOT EDIT.

package device

import "github.com/spf13/cobra"

var DeviceCmd = &cobra.Command{
	Use:   "device",
	Short: "终端管理",
	Long:  `终端管理相关命令。`,
}

func init() {
	DeviceCmd.AddCommand(ListCmd)
	DeviceCmd.AddCommand(DetailCmd)
	DeviceCmd.AddCommand(BindingDetailCmd)
	DeviceCmd.AddCommand(BindingUpdateCmd)
	DeviceCmd.AddCommand(BindingDeleteCmd)
}
