// Code generated by generate_ddr_cli.py. DO NOT EDIT.

package device

import (
	"context"

	"github.com/ddr/ddr-cli-generated/products/ddr/client"
	"github.com/spf13/cobra"
)

type ListCmdParams struct {
	Page         string   `json:"page"`          // 第几页
	Limit        string   `json:"limit"`         // 每页条数，默认100
	Search       string   `json:"search"`        // 模糊检索
	Ip           string   `json:"ip"`            // IP 地址
	ConsoleUser  string   `json:"console_user"`  // 控制台用户
	AgentVersion string   `json:"agent_version"` // Agent 版本
	HealthStatus string   `json:"health_status"` // normal:正常, abnormal异常
	StaffId      string   `json:"staff_id"`      // 员工ID
	ConnStatus   string   `json:"conn_status"`   // online:在线 offline: 离线 abnormal:失效(长期离线)
	SerialNumber string   `json:"serial_number"` // 序列号
	LifeStatus   []string `json:"life_status"`   // uninstalled: 已卸载, uninstalling: 卸载中, working: 工作中
	Status       []string `json:"status"`        // 状态
	Mac          string   `json:"mac"`           // MAC 地址
}

var list_params ListCmdParams

var ListCmd = &cobra.Command{
	Use:   "list",
	Short: "查询设备列表",
	Long:  `查询设备列表`,
	RunE: func(cmd *cobra.Command, args []string) error {

		pathParams := map[string]interface{}{}

		queryParams := map[string]interface{}{}
		if cmd.Flags().Changed("page") {
			queryParams["page"] = list_params.Page
		}
		if cmd.Flags().Changed("limit") {
			queryParams["limit"] = list_params.Limit
		}
		if cmd.Flags().Changed("search") {
			queryParams["search"] = list_params.Search
		}
		body := map[string]interface{}{}
		if cmd.Flags().Changed("ip") {
			body["ip"] = list_params.Ip
		}
		if cmd.Flags().Changed("console-user") {
			body["console_user"] = list_params.ConsoleUser
		}
		if cmd.Flags().Changed("agent-version") {
			body["agent_version"] = list_params.AgentVersion
		}
		if cmd.Flags().Changed("health-status") {
			body["health_status"] = list_params.HealthStatus
		}
		if cmd.Flags().Changed("staff-id") {
			body["staff_id"] = list_params.StaffId
		}
		if cmd.Flags().Changed("conn-status") {
			body["conn_status"] = list_params.ConnStatus
		}
		if cmd.Flags().Changed("serial-number") {
			body["serial_number"] = list_params.SerialNumber
		}
		if cmd.Flags().Changed("life-status") {
			body["life_status"] = list_params.LifeStatus
		}
		if cmd.Flags().Changed("status") {
			body["status"] = list_params.Status
		}
		if cmd.Flags().Changed("mac") {
			body["mac"] = list_params.Mac
		}
		return client.GetClient().Do(cmd, context.Background(), "POST", "/v1/device/list", pathParams, queryParams, body)
	},
}

func init() {
	ListCmd.Flags().StringVar(&list_params.Page, "page", "", "第几页")
	ListCmd.Flags().StringVar(&list_params.Limit, "limit", "", "每页条数，默认100")
	ListCmd.Flags().StringVar(&list_params.Search, "search", "", "模糊检索")
	ListCmd.Flags().StringVar(&list_params.Ip, "ip", "", "IP 地址")
	ListCmd.Flags().StringVar(&list_params.ConsoleUser, "console-user", "", "控制台用户")
	ListCmd.Flags().StringVar(&list_params.AgentVersion, "agent-version", "", "Agent 版本")
	ListCmd.Flags().StringVar(&list_params.HealthStatus, "health-status", "", "normal:正常, abnormal异常")
	ListCmd.Flags().StringVar(&list_params.StaffId, "staff-id", "", "员工ID")
	ListCmd.Flags().StringVar(&list_params.ConnStatus, "conn-status", "", "online:在线 offline: 离线 abnormal:失效(长期离线)")
	ListCmd.Flags().StringVar(&list_params.SerialNumber, "serial-number", "", "序列号")
	ListCmd.Flags().StringSliceVar(&list_params.LifeStatus, "life-status", nil, "uninstalled: 已卸载, uninstalling: 卸载中, working: 工作中")
	ListCmd.Flags().StringSliceVar(&list_params.Status, "status", nil, "状态")
	ListCmd.Flags().StringVar(&list_params.Mac, "mac", "", "MAC 地址")
}
