// Code generated by generate_ddr_cli.py. DO NOT EDIT.

package network_policy

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/ddr/ddr-cli-generated/products/ddr/client"
	"github.com/spf13/cobra"
)

type CreateCmdParams struct {
	Name             string                   `json:"name"`               // 策略名
	Description      string                   `json:"description"`        // 策略描述
	PeriodCategory   string                   `json:"period_category"`    // 下发时效
	Scope            string                   `json:"scope"`              // 下发范围 全局: global 部分: common
	SourceScope      string                   `json:"source_scope"`       // 管控软件 全局: global 部分: common
	ControlOptions   map[string]interface{}   `json:"control_options"`    // 联网策略的ip/host名单
	ActionTemplateId string                   `json:"action_template_id"` // 处置模板ID
	SoftwareSource   []map[string]interface{} `json:"software_source"`    // 管控的软件信息
	BindingConfig    map[string]interface{}   `json:"binding_config"`     // 绑定配置
	Action           string                   `json:"action"`             // 处置动作
	PeriodOptions    map[string]interface{}   `json:"period_options"`     // 生效周期配置
}

var create_params CreateCmdParams
var CreateControlOptionsJSON string
var CreateSoftwareSourceJSON string
var CreateBindingConfigJSON string
var CreatePeriodOptionsJSON string

var CreateCmd = &cobra.Command{
	Use:   "create",
	Short: "创建进程联网策略",
	Long:  `创建进程联网策略`,
	RunE: func(cmd *cobra.Command, args []string) error {
		if CreateControlOptionsJSON != "" {
			if err := json.Unmarshal([]byte(CreateControlOptionsJSON), &create_params.ControlOptions); err != nil {
				return fmt.Errorf("parse control-options: %w", err)
			}
		}
		if CreateSoftwareSourceJSON != "" {
			if err := json.Unmarshal([]byte(CreateSoftwareSourceJSON), &create_params.SoftwareSource); err != nil {
				return fmt.Errorf("parse software-source: %w", err)
			}
		}
		if CreateBindingConfigJSON != "" {
			if err := json.Unmarshal([]byte(CreateBindingConfigJSON), &create_params.BindingConfig); err != nil {
				return fmt.Errorf("parse binding-config: %w", err)
			}
		}
		if CreatePeriodOptionsJSON != "" {
			if err := json.Unmarshal([]byte(CreatePeriodOptionsJSON), &create_params.PeriodOptions); err != nil {
				return fmt.Errorf("parse period-options: %w", err)
			}
		}
		pathParams := map[string]interface{}{}

		queryParams := map[string]interface{}{}

		body := map[string]interface{}{}
		if cmd.Flags().Changed("name") {
			body["name"] = create_params.Name
		}
		if cmd.Flags().Changed("description") {
			body["description"] = create_params.Description
		}
		if cmd.Flags().Changed("period-category") {
			body["period_category"] = create_params.PeriodCategory
		}
		if cmd.Flags().Changed("scope") {
			body["scope"] = create_params.Scope
		}
		if cmd.Flags().Changed("source-scope") {
			body["source_scope"] = create_params.SourceScope
		}
		if cmd.Flags().Changed("control-options") {
			body["control_options"] = create_params.ControlOptions
		}
		if cmd.Flags().Changed("action-template-id") {
			body["action_template_id"] = create_params.ActionTemplateId
		}
		if cmd.Flags().Changed("software-source") {
			body["software_source"] = create_params.SoftwareSource
		}
		if cmd.Flags().Changed("binding-config") {
			body["binding_config"] = create_params.BindingConfig
		}
		if cmd.Flags().Changed("action") {
			body["action"] = create_params.Action
		}
		if cmd.Flags().Changed("period-options") {
			body["period_options"] = create_params.PeriodOptions
		}
		return client.GetClient().Do(cmd, context.Background(), "POST", "/v1/policy/network/create", pathParams, queryParams, body)
	},
}

func init() {
	CreateCmd.Flags().StringVar(&create_params.Name, "name", "", "策略名")
	CreateCmd.Flags().StringVar(&create_params.Description, "description", "", "策略描述")
	CreateCmd.Flags().StringVar(&create_params.PeriodCategory, "period-category", "", "下发时效")
	CreateCmd.Flags().StringVar(&create_params.Scope, "scope", "", "下发范围 全局: global 部分: common")
	CreateCmd.Flags().StringVar(&create_params.SourceScope, "source-scope", "", "管控软件 全局: global 部分: common")
	CreateCmd.Flags().StringVar(&CreateControlOptionsJSON, "control-options", "", "联网策略的ip/host名单 (JSON, e.g. {\"whitelist\": [{\"multi\": false, \"field\": \"\", \"protocol\": \"\", \"value\": \"\"}]})")
	CreateCmd.Flags().StringVar(&create_params.ActionTemplateId, "action-template-id", "", "处置模板ID")
	CreateCmd.Flags().StringVar(&CreateSoftwareSourceJSON, "software-source", "", "管控的软件信息 (JSON, e.g. [{\"key\": \"\", \"family\": \"\", \"software_name\": \"\", \"software_type\": \"\", \"options\": [{\"key\": \"...\", \"field\": \"...\", \"value\": \"...\"}]}])")
	CreateCmd.Flags().StringVar(&CreateBindingConfigJSON, "binding-config", "", "绑定配置 (JSON, e.g. {\"source\": \"\", \"include\": {\"dept_ids\": [\"\"], \"staff_ids\": [\"\"], \"staff_tag_ids\": [\"\"], \"device_ids\": [\"\"], \"device_tag_ids\": [\"\"]}, \"exclude\": {\"dept_ids\": [\"\"], \"staff_ids\": [\"\"], \"staff_tag_ids\": [\"\"], \"device_ids\": [\"\"], \"device_tag_ids\": [\"\"]}})")
	CreateCmd.Flags().StringVar(&create_params.Action, "action", "", "处置动作")
	CreateCmd.Flags().StringVar(&CreatePeriodOptionsJSON, "period-options", "", "生效周期配置 (JSON, e.g. {\"period_hours_value\": [{\"begin\": \"\", \"end\": \"\", \"week\": 0}], \"period_value\": [\"\"]})")
	_ = CreateCmd.MarkFlagRequired("name")
	_ = CreateCmd.MarkFlagRequired("period-category")
	_ = CreateCmd.MarkFlagRequired("scope")
	_ = CreateCmd.MarkFlagRequired("source-scope")
	_ = CreateCmd.MarkFlagRequired("control-options")
	_ = CreateCmd.MarkFlagRequired("action-template-id")
	_ = CreateCmd.MarkFlagRequired("software-source")
	_ = CreateCmd.MarkFlagRequired("binding-config")
	_ = CreateCmd.MarkFlagRequired("action")
}
