// Code generated by generate_ddr_cli.py. DO NOT EDIT.

package network_policy

import "github.com/spf13/cobra"

var NetworkPolicyCmd = &cobra.Command{
	Use:   "network_policy",
	Short: "联网管控策略",
	Long:  `联网管控策略相关命令。`,
}

func init() {
	NetworkPolicyCmd.AddCommand(CreateCmd)
	NetworkPolicyCmd.AddCommand(DeleteCmd)
	NetworkPolicyCmd.AddCommand(StatusUpdateCmd)
}
