// Code generated by generate_ddr_cli.py. DO NOT EDIT.

package devicetag

import (
	"context"

	"github.com/ddr/ddr-cli-generated/products/ddr/client"
	"github.com/spf13/cobra"
)

type CreateCmdParams struct {
	Name      string   `json:"name"`       // 名称
	DeviceIds []string `json:"device_ids"` // 同时要绑定的设备，空数组或者空则意味着创建时不绑定
}

var create_params CreateCmdParams

var CreateCmd = &cobra.Command{
	Use:   "create",
	Short: "创建设备标签",
	Long:  `创建设备标签`,
	RunE: func(cmd *cobra.Command, args []string) error {

		pathParams := map[string]interface{}{}

		queryParams := map[string]interface{}{}

		body := map[string]interface{}{}
		if cmd.Flags().Changed("name") {
			body["name"] = create_params.Name
		}
		if cmd.Flags().Changed("device-ids") {
			body["device_ids"] = create_params.DeviceIds
		}
		return client.GetClient().Do(cmd, context.Background(), "POST", "/v1/devicetag/create", pathParams, queryParams, body)
	},
}

func init() {
	CreateCmd.Flags().StringVar(&create_params.Name, "name", "", "名称")
	CreateCmd.Flags().StringSliceVar(&create_params.DeviceIds, "device-ids", nil, "同时要绑定的设备，空数组或者空则意味着创建时不绑定")
	_ = CreateCmd.MarkFlagRequired("name")
}
