// Code generated by generate_ddr_cli.py. DO NOT EDIT.

package devicetag

import "github.com/spf13/cobra"

var DevicetagCmd = &cobra.Command{
	Use:   "devicetag",
	Short: "终端标签管理",
	Long:  `终端标签管理相关命令。`,
}

func init() {
	DevicetagCmd.AddCommand(ListCmd)
	DevicetagCmd.AddCommand(MemberBatchAddCmd)
	DevicetagCmd.AddCommand(MemberBatchRemoveCmd)
	DevicetagCmd.AddCommand(CreateCmd)
	DevicetagCmd.AddCommand(UpdateCmd)
	DevicetagCmd.AddCommand(DeleteCmd)
}
