// Code generated by generate_ddr_cli.py. DO NOT EDIT.

package devicetag

import (
	"context"

	"github.com/ddr/ddr-cli-generated/products/ddr/client"
	"github.com/spf13/cobra"
)

type MemberBatchAddCmdParams struct {
	TagId     string   `json:"tag_id"`     // 标签ID
	DeviceIds []string `json:"device_ids"` // 设备uid列表
}

var member_batch_add_params MemberBatchAddCmdParams

var MemberBatchAddCmd = &cobra.Command{
	Use:   "member_batch_add",
	Short: "设备标签批量添加设备",
	Long:  `设备标签批量添加设备`,
	RunE: func(cmd *cobra.Command, args []string) error {

		pathParams := map[string]interface{}{}

		queryParams := map[string]interface{}{}

		body := map[string]interface{}{}
		if cmd.Flags().Changed("tag-id") {
			body["tag_id"] = member_batch_add_params.TagId
		}
		if cmd.Flags().Changed("device-ids") {
			body["device_ids"] = member_batch_add_params.DeviceIds
		}
		return client.GetClient().Do(cmd, context.Background(), "POST", "/v1/devicetag/member/batch_add", pathParams, queryParams, body)
	},
}

func init() {
	MemberBatchAddCmd.Flags().StringVar(&member_batch_add_params.TagId, "tag-id", "", "标签ID")
	MemberBatchAddCmd.Flags().StringSliceVar(&member_batch_add_params.DeviceIds, "device-ids", nil, "设备uid列表")
	_ = MemberBatchAddCmd.MarkFlagRequired("tag-id")
	_ = MemberBatchAddCmd.MarkFlagRequired("device-ids")
}
