// Code generated by generate_ddr_cli.py. DO NOT EDIT.

package devicetag

import (
	"context"

	"github.com/ddr/ddr-cli-generated/products/ddr/client"
	"github.com/spf13/cobra"
)

type UpdateCmdParams struct {
	TagId     string   `json:"tag_id"`     // 标签唯一ID
	Name      string   `json:"name"`       // 标签名
	DeviceIds []string `json:"device_ids"` // 绑定给什么设备，如果为空则不绑定
}

var update_params UpdateCmdParams

var UpdateCmd = &cobra.Command{
	Use:   "update",
	Short: "更新设备标签",
	Long:  `更新设备标签`,
	RunE: func(cmd *cobra.Command, args []string) error {

		pathParams := map[string]interface{}{}

		queryParams := map[string]interface{}{}

		body := map[string]interface{}{}
		if cmd.Flags().Changed("tag-id") {
			body["tag_id"] = update_params.TagId
		}
		if cmd.Flags().Changed("name") {
			body["name"] = update_params.Name
		}
		if cmd.Flags().Changed("device-ids") {
			body["device_ids"] = update_params.DeviceIds
		}
		return client.GetClient().Do(cmd, context.Background(), "POST", "/v1/devicetag/update", pathParams, queryParams, body)
	},
}

func init() {
	UpdateCmd.Flags().StringVar(&update_params.TagId, "tag-id", "", "标签唯一ID")
	UpdateCmd.Flags().StringVar(&update_params.Name, "name", "", "标签名")
	UpdateCmd.Flags().StringSliceVar(&update_params.DeviceIds, "device-ids", nil, "绑定给什么设备，如果为空则不绑定")
	_ = UpdateCmd.MarkFlagRequired("tag-id")
	_ = UpdateCmd.MarkFlagRequired("name")
}
