// Code generated by generate_ddr_cli.py. DO NOT EDIT.

package software_policy

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/ddr/ddr-cli-generated/products/ddr/client"
	"github.com/spf13/cobra"
)

type CreateCmdParams struct {
	Name            string                   `json:"name"`             // 策略名
	Description     string                   `json:"description"`      // 策略描述
	PeriodCategory  string                   `json:"period_category"`  // 生效周期
	Scope           string                   `json:"scope"`            // 下发范围 全局：global 部分：common
	Action          string                   `json:"action"`           // 处置动作
	BindingConfig   map[string]interface{}   `json:"binding_config"`   // 绑定配置
	PeriodOptions   map[string]interface{}   `json:"period_options"`   // 生效周期配置
	Category        string                   `json:"category"`         // 策略类别
	ControlCategory string                   `json:"control_category"` // 管控类别
	KillRunning     bool                     `json:"kill_running"`     // 是否结束运行中的进程
	RunModel        []string                 `json:"run_model"`        // 运行模式
	SourceScope     string                   `json:"source_scope"`     // 软件范围
	SoftwareSource  []map[string]interface{} `json:"software_source"`  // 软件来源列表
}

var create_params CreateCmdParams
var CreateBindingConfigJSON string
var CreatePeriodOptionsJSON string
var CreateSoftwareSourceJSON string

var CreateCmd = &cobra.Command{
	Use:   "create",
	Short: "创建软件管控策略",
	Long:  `创建软件管控策略`,
	RunE: func(cmd *cobra.Command, args []string) error {
		if CreateBindingConfigJSON != "" {
			if err := json.Unmarshal([]byte(CreateBindingConfigJSON), &create_params.BindingConfig); err != nil {
				return fmt.Errorf("parse binding-config: %w", err)
			}
		}
		if CreatePeriodOptionsJSON != "" {
			if err := json.Unmarshal([]byte(CreatePeriodOptionsJSON), &create_params.PeriodOptions); err != nil {
				return fmt.Errorf("parse period-options: %w", err)
			}
		}
		if CreateSoftwareSourceJSON != "" {
			if err := json.Unmarshal([]byte(CreateSoftwareSourceJSON), &create_params.SoftwareSource); err != nil {
				return fmt.Errorf("parse software-source: %w", err)
			}
		}
		pathParams := map[string]interface{}{}

		queryParams := map[string]interface{}{}

		body := map[string]interface{}{}
		if cmd.Flags().Changed("name") {
			body["name"] = create_params.Name
		}
		if cmd.Flags().Changed("description") {
			body["description"] = create_params.Description
		}
		if cmd.Flags().Changed("period-category") {
			body["period_category"] = create_params.PeriodCategory
		}
		if cmd.Flags().Changed("scope") {
			body["scope"] = create_params.Scope
		}
		if cmd.Flags().Changed("action") {
			body["action"] = create_params.Action
		}
		if cmd.Flags().Changed("binding-config") {
			body["binding_config"] = create_params.BindingConfig
		}
		if cmd.Flags().Changed("period-options") {
			body["period_options"] = create_params.PeriodOptions
		}
		if cmd.Flags().Changed("category") {
			body["category"] = create_params.Category
		}
		if cmd.Flags().Changed("control-category") {
			body["control_category"] = create_params.ControlCategory
		}
		if cmd.Flags().Changed("kill-running") {
			body["kill_running"] = create_params.KillRunning
		}
		if cmd.Flags().Changed("run-model") {
			body["run_model"] = create_params.RunModel
		}
		if cmd.Flags().Changed("source-scope") {
			body["source_scope"] = create_params.SourceScope
		}
		if cmd.Flags().Changed("software-source") {
			body["software_source"] = create_params.SoftwareSource
		}
		return client.GetClient().Do(cmd, context.Background(), "POST", "/v1/policy/software/create", pathParams, queryParams, body)
	},
}

func init() {
	CreateCmd.Flags().StringVar(&create_params.Name, "name", "", "策略名")
	CreateCmd.Flags().StringVar(&create_params.Description, "description", "", "策略描述")
	CreateCmd.Flags().StringVar(&create_params.PeriodCategory, "period-category", "", "生效周期")
	CreateCmd.Flags().StringVar(&create_params.Scope, "scope", "", "下发范围 全局：global 部分：common")
	CreateCmd.Flags().StringVar(&create_params.Action, "action", "", "处置动作")
	CreateCmd.Flags().StringVar(&CreateBindingConfigJSON, "binding-config", "", "绑定配置 (JSON, e.g. {\"source\": \"\", \"include\": {\"dept_ids\": [\"\"], \"staff_ids\": [\"\"], \"staff_tag_ids\": [\"\"], \"device_ids\": [\"\"], \"device_tag_ids\": [\"\"]}, \"exclude\": {}})")
	CreateCmd.Flags().StringVar(&CreatePeriodOptionsJSON, "period-options", "", "生效周期配置 (JSON, e.g. {})")
	CreateCmd.Flags().StringVar(&create_params.Category, "category", "", "策略类别")
	CreateCmd.Flags().StringVar(&create_params.ControlCategory, "control-category", "", "管控类别")
	CreateCmd.Flags().BoolVar(&create_params.KillRunning, "kill-running", false, "是否结束运行中的进程")
	CreateCmd.Flags().StringSliceVar(&create_params.RunModel, "run-model", nil, "运行模式")
	CreateCmd.Flags().StringVar(&create_params.SourceScope, "source-scope", "", "软件范围")
	CreateCmd.Flags().StringVar(&CreateSoftwareSourceJSON, "software-source", "", "软件来源列表 (JSON, e.g. [{\"software_name\": \"\", \"software_type\": \"\", \"family\": \"\", \"options\": [{\"field\": \"...\", \"value\": \"...\"}]}])")
	_ = CreateCmd.MarkFlagRequired("name")
	_ = CreateCmd.MarkFlagRequired("description")
	_ = CreateCmd.MarkFlagRequired("period-category")
	_ = CreateCmd.MarkFlagRequired("scope")
	_ = CreateCmd.MarkFlagRequired("action")
	_ = CreateCmd.MarkFlagRequired("binding-config")
	_ = CreateCmd.MarkFlagRequired("period-options")
	_ = CreateCmd.MarkFlagRequired("category")
	_ = CreateCmd.MarkFlagRequired("control-category")
	_ = CreateCmd.MarkFlagRequired("kill-running")
	_ = CreateCmd.MarkFlagRequired("run-model")
	_ = CreateCmd.MarkFlagRequired("source-scope")
	_ = CreateCmd.MarkFlagRequired("software-source")
}
