// Code generated by generate_ddr_cli.py. DO NOT EDIT.

package software_policy

import (
	"context"

	"github.com/ddr/ddr-cli-generated/products/ddr/client"
	"github.com/spf13/cobra"
)

type DeleteCmdParams struct {
	PolicyId string `json:"policy_id"` // 策略ID
}

var delete_params DeleteCmdParams

var DeleteCmd = &cobra.Command{
	Use:   "delete",
	Short: "删除软件管控策略",
	Long:  `删除软件管控策略`,
	RunE: func(cmd *cobra.Command, args []string) error {

		pathParams := map[string]interface{}{}

		queryParams := map[string]interface{}{}

		body := map[string]interface{}{}
		if cmd.Flags().Changed("policy-id") {
			body["policy_id"] = delete_params.PolicyId
		}
		return client.GetClient().Do(cmd, context.Background(), "POST", "/v1/policy/software/delete", pathParams, queryParams, body)
	},
}

func init() {
	DeleteCmd.Flags().StringVar(&delete_params.PolicyId, "policy-id", "", "策略ID")
	_ = DeleteCmd.MarkFlagRequired("policy-id")
}
