// Code generated by generate_ddr_cli.py. DO NOT EDIT.

package software_policy

import (
	"context"

	"github.com/ddr/ddr-cli-generated/products/ddr/client"
	"github.com/spf13/cobra"
)

type ListCmdParams struct {
	Action string `json:"action"` // 处置动作
	Status string `json:"status"` // 状态
}

var list_params ListCmdParams

var ListCmd = &cobra.Command{
	Use:   "list",
	Short: "查询软件管控策略列表",
	Long:  `查询软件管控策略列表`,
	RunE: func(cmd *cobra.Command, args []string) error {

		pathParams := map[string]interface{}{}

		queryParams := map[string]interface{}{}

		body := map[string]interface{}{}
		if cmd.Flags().Changed("action") {
			body["action"] = list_params.Action
		}
		if cmd.Flags().Changed("status") {
			body["status"] = list_params.Status
		}
		return client.GetClient().Do(cmd, context.Background(), "POST", "/v1/policy/software/list", pathParams, queryParams, body)
	},
}

func init() {
	ListCmd.Flags().StringVar(&list_params.Action, "action", "", "处置动作")
	ListCmd.Flags().StringVar(&list_params.Status, "status", "", "状态")
	_ = ListCmd.MarkFlagRequired("action")
	_ = ListCmd.MarkFlagRequired("status")
}
