// Code generated by generate_ddr_cli.py. DO NOT EDIT.

package software_policy

import "github.com/spf13/cobra"

var SoftwarePolicyCmd = &cobra.Command{
	Use:   "software_policy",
	Short: "软件管控策略",
	Long:  `软件管控策略相关命令。`,
}

func init() {
	SoftwarePolicyCmd.AddCommand(ListCmd)
	SoftwarePolicyCmd.AddCommand(CreateCmd)
	SoftwarePolicyCmd.AddCommand(DeleteCmd)
	SoftwarePolicyCmd.AddCommand(StatusUpdateCmd)
}
