// Code generated by generate_ddr_cli.py. DO NOT EDIT.

package software_policy

import (
	"context"

	"github.com/ddr/ddr-cli-generated/products/ddr/client"
	"github.com/spf13/cobra"
)

type StatusUpdateCmdParams struct {
	PolicyId string `json:"policy_id"` // 策略ID
	Status   string `json:"status"`    // 状态
}

var status_update_params StatusUpdateCmdParams

var StatusUpdateCmd = &cobra.Command{
	Use:   "status_update",
	Short: "修改软件管控策略状态",
	Long:  `修改软件管控策略状态`,
	RunE: func(cmd *cobra.Command, args []string) error {

		pathParams := map[string]interface{}{}

		queryParams := map[string]interface{}{}

		body := map[string]interface{}{}
		if cmd.Flags().Changed("policy-id") {
			body["policy_id"] = status_update_params.PolicyId
		}
		if cmd.Flags().Changed("status") {
			body["status"] = status_update_params.Status
		}
		return client.GetClient().Do(cmd, context.Background(), "POST", "/v1/policy/software/status/update", pathParams, queryParams, body)
	},
}

func init() {
	StatusUpdateCmd.Flags().StringVar(&status_update_params.PolicyId, "policy-id", "", "策略ID")
	StatusUpdateCmd.Flags().StringVar(&status_update_params.Status, "status", "", "状态")
	_ = StatusUpdateCmd.MarkFlagRequired("policy-id")
	_ = StatusUpdateCmd.MarkFlagRequired("status")
}
