// Code generated by generate_ddr_cli.py. DO NOT EDIT.

package software

import (
	"context"

	"github.com/ddr/ddr-cli-generated/products/ddr/client"
	"github.com/spf13/cobra"
)

type ListCmdParams struct {
	Page   string `json:"page"`   // 第几页
	Limit  string `json:"limit"`  // 每页条数
	Search string `json:"search"` // 模糊检索
}

var list_params ListCmdParams

var ListCmd = &cobra.Command{
	Use:   "list",
	Short: "查询软件列表",
	Long:  `查询软件列表`,
	RunE: func(cmd *cobra.Command, args []string) error {

		pathParams := map[string]interface{}{}

		queryParams := map[string]interface{}{}
		if cmd.Flags().Changed("page") {
			queryParams["page"] = list_params.Page
		}
		if cmd.Flags().Changed("limit") {
			queryParams["limit"] = list_params.Limit
		}
		if cmd.Flags().Changed("search") {
			queryParams["search"] = list_params.Search
		}
		body := map[string]interface{}{}
		return client.GetClient().Do(cmd, context.Background(), "POST", "/v1/softwaremanager/list", pathParams, queryParams, body)
	},
}

func init() {
	ListCmd.Flags().StringVar(&list_params.Page, "page", "", "第几页")
	ListCmd.Flags().StringVar(&list_params.Limit, "limit", "", "每页条数")
	ListCmd.Flags().StringVar(&list_params.Search, "search", "", "模糊检索")
	_ = ListCmd.MarkFlagRequired("page")
	_ = ListCmd.MarkFlagRequired("limit")
	_ = ListCmd.MarkFlagRequired("search")
}
