// Code generated by generate_ddr_cli.py. DO NOT EDIT.

package software

import "github.com/spf13/cobra"

var SoftwareCmd = &cobra.Command{
	Use:   "software",
	Short: "软件管理",
	Long:  `软件管理相关命令。`,
}

func init() {
	SoftwareCmd.AddCommand(ListCmd)
}
