// Code generated by generate_ddr_cli.py. DO NOT EDIT.

package ddr

import (
	"github.com/ddr/ddr-cli-generated/products/ddr/client"
	"github.com/spf13/cobra"

	"github.com/ddr/ddr-cli-generated/products/ddr/cli/approval"
	"github.com/ddr/ddr-cli-generated/products/ddr/cli/channel"
	"github.com/ddr/ddr-cli-generated/products/ddr/cli/device"
	"github.com/ddr/ddr-cli-generated/products/ddr/cli/devicetag"
	"github.com/ddr/ddr-cli-generated/products/ddr/cli/externaldevice_policy"
	"github.com/ddr/ddr-cli-generated/products/ddr/cli/network_policy"
	"github.com/ddr/ddr-cli-generated/products/ddr/cli/software"
	"github.com/ddr/ddr-cli-generated/products/ddr/cli/software_policy"
	"github.com/ddr/ddr-cli-generated/products/ddr/cli/staff"
	"github.com/ddr/ddr-cli-generated/products/ddr/cli/stafftag"
	"github.com/ddr/ddr-cli-generated/products/ddr/cli/token"
)

var (
	baseURL     string
	companyID   string
	authToken   string
	language    string
	debugMode   bool
	insecureTLS bool
	format      string
	noTrunc     bool
	dryRun      bool
)

var rootCmd = &cobra.Command{
	Use:   "ddr",
	Short: "DDR CLI",
	Long:  `DDR CLI generated from DDR_openapi.json.`,
	PersistentPreRun: func(cmd *cobra.Command, args []string) {
		client.SetBaseURL(baseURL)
		client.SetCompanyID(companyID)
		client.SetToken(authToken)
		client.SetLanguage(language)
		client.SetDebug(debugMode)
		client.SetInsecureTLS(insecureTLS)
		client.SetDryRun(dryRun)
		client.SetFormat(format)
		client.SetNoTrunc(noTrunc)
	},
}

func init() {
	rootCmd.PersistentFlags().StringVar(&baseURL, "url", "", "DDR API base URL, e.g. https://127.0.0.1:8443/openapi")
	rootCmd.PersistentFlags().StringVar(&companyID, "company-id", "", "Value for X-CS-Header-Company")
	rootCmd.PersistentFlags().StringVar(&authToken, "token", "", "Token value without the Token prefix")
	rootCmd.PersistentFlags().StringVar(&language, "lang", "zh", "Accept-Language header")
	rootCmd.PersistentFlags().BoolVar(&debugMode, "debug", false, "Send X-CS-Header-Debug: true")
	rootCmd.PersistentFlags().BoolVar(&insecureTLS, "insecure", false, "Skip TLS certificate verification")
	rootCmd.PersistentFlags().BoolVar(&dryRun, "dry-run", false, "Print the request without sending it")
	rootCmd.PersistentFlags().StringVarP(&format, "format", "f", "json", "Output format (json or text)")
	rootCmd.PersistentFlags().BoolVar(&noTrunc, "no-trunc", false, "Reserved for future text formatting support")

	rootCmd.AddCommand(approval.ApprovalCmd)
	rootCmd.AddCommand(channel.ChannelCmd)
	rootCmd.AddCommand(device.DeviceCmd)
	rootCmd.AddCommand(devicetag.DevicetagCmd)
	rootCmd.AddCommand(externaldevice_policy.ExternaldevicePolicyCmd)
	rootCmd.AddCommand(network_policy.NetworkPolicyCmd)
	rootCmd.AddCommand(software.SoftwareCmd)
	rootCmd.AddCommand(software_policy.SoftwarePolicyCmd)
	rootCmd.AddCommand(staff.StaffCmd)
	rootCmd.AddCommand(stafftag.StafftagCmd)
	rootCmd.AddCommand(token.TokenCmd)
}

func NewCommand() *cobra.Command {
	return rootCmd
}
